"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['bugsinbox.py']
DATA_FILES = ['bullet.wav', 'king_beetle_transp.png', 'ladybug_transp.png', 'mexican_bean_beetle_transp.png', 'mouselemur.png','tigerbeetle2.png']
OPTIONS = {
    'iconfile': '/Users/beerli/Sources/python-snippets/showcases/bugsinbox/bugsinbox.icns',
    'plist': {'CFBundleShortVersionString':'0.1.0',}}


setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
